### PR TITLE
Add .gitignore and new page setup (narrow margins)

### LINKED ISSUE #2: Margins too big
Since moving to 1.02 the page format has changed so the text on pages take up very little space of the actual page. That is, margins are pretty big, see below. Hope this can get fixed so we are not wasting too much paper.

image

### PR DESCRIPTION
**Pull request by nietras**
Resolve #2

### CODE REVIEW

**Comment by nietras** [comment]
@AgnerF I will make another pull request with margin changes after this has been accepted.

**Comment by nietras** [comment]
@AgnerF thanks for merging apparently this pull request contained the margin changes too, let me know if you approve of these. Basically, I just change page to be A4 and reduced margins so less paper is needed.

**Comment by nietras** [comment]
Closes #2

**Comment by AgnerF** [comment]
It looks nice. Thanks for the help. 
But can you tell why there is a blank page before each chapter?

**Comment by AgnerF** [comment]
I found out. The blank pages are there because you have set the layout to 2-sided and it starts each chapter on an odd page. There are no blank pages if you change to 1-sided. 

I think that few people will print 100 pages anyway. Most people will read it on the screen, so I prefer the 1-sided layout. There is no problem printing it 2-sided even if the layout is 1-sided.

**Comment by nietras** [comment]
Yes, it's just my personal preference since it makes two sided printing
easier, especially when printing a specific chapter. It is fine if you
remove it, it's just my preferences. You might remove the 5mm extra margin
for two sided as well.

**Pull request merged**
